# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time', models.FloatField()),
                ('serves', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('feedback', models.TextField()),
                ('keywords', models.CharField(max_length=50)),
            ],
        ),
    ]
