# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171103_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantry',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
