# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_register'),
        ('dashboard', '0003_user'),
    ]

    operations = [
    ]
