# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20171205_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_display',
            field=models.TextField(default=''),
        ),
    ]
