# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20171206_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pantry',
            old_name='encoded_pantry_ingredients',
            new_name='pantry_ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='encoded_recipe_ingredients',
            new_name='recipe_ingredients',
        ),
    ]
